project:
  title: "Lab Reports"
  output-dir: output

title-block-banner: true
code-fold: true
page-layout: article 
author: 
  - name: Matthew Lyn 
    email: mml167@georgetown.edu
format:
  html:
    toc: true
    number-sections: true
    colorlinks: true
    linestretch: 1.15
    font-size: 12
    mainfont: "Atkinson Hyperlegible Next"
    sansfont: "Newsreader 36pt"
    mermaid: 
      theme: neutral 
    theme:
      light: flatly
      dark: solar 
  pdf:
    toc: true
    number-sections: true
    colorlinks: true
    linestretch: 1.15
    font-size: 12
    mainfont: "Atkinson Hyperlegible Next"
    sansfont: "Newsreader 36pt"
    tbl-colwidths: auto
    lof: true
    lot: true
    mermaid:
      theme: neutral